### ISSUE TITLE
Set up a development environment

### ISSUE THREAD

**Issue by jonrh** [jonrh/rotten-tube#1]
I think [WebStorm 11](https://www.jetbrains.com/webstorm/) might be the best fit for us. It's fresh of the press with ES2015 syntax support and we as UCD students get it for free.

**Todo**:
- [x] set up WebStorm and node.js on all 3 computers
- [x] create a ES6 Babel bootstrap project
- [x] bootstrap a React application that displays some text
- [x] create node.js projects with some ES6 code

**Comment by jonrh** [comment]
Completed in 07b2da4ff96b148e202ca60554b076d2773311e6.
