### ISSUE TITLE
Set up AWS RDS MySQL

### ISSUE THREAD

**Issue by jonrh** [jonrh/rotten-tube#2]
For the database of this project we'll use AWS RDS MySQL.
# Table schema
- ID, auto incrementing integer
- name, string
# Tasks
- [x] Create a AWS RDS MySQL instance
- [x] Figure out how authentication works
- [x] Create the table _names_
- [x] Insert 3 names into the table: "Jill", "Jón", and "Yifei"
- [x] Figure out how to use Node environment variables to store authentication credentials (so we don't commit them to the repository)
- [x] Fetch those 3 names from JavaScript code

**Comment by jonrh** [comment]
All done now, see 7b590f9481ac1d4d1d7d55eddf2e2549dcf1840d
